apiVersion: v2
name: directus
description: A Helm chart for installing Directus on Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
version: 0.9.09
||||||| f3b1c4b
version: 0.9.06
=======
version: 0.9.08
>>>>>>> 7a12cc01ec0961ccaa4b13582846f59efb16717d

# This is the version number of the application being deployed. They should reflect the version
# the application is using.
appVersion: "11.1.0"

maintainers:
  - name: Mikke Schirén
    email: mikke.schiren@digitalist.se
    url: https://www.digitalist.se/

dependencies:
  - name: mariadb
    version: "15.0.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mariadb.enabled
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
