apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "directus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node"]
          args: ["/directus/cli.js", "bootstrap"]
          env:
            {{- if .Values.ingress.enabled }}
            - name: PUBLIC_URL
              value: http{{ if .Values.ingress.tls }}s{{ end }}://{{(index .Values.ingress.hosts 0).host }}
            {{- end }}
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-secrets
                  key: key
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-secrets
                  key: secret
            {{- if .Values.mariadb.enabled }}
            - name: DB_DATABASE
              value: {{ .Values.mariadb.auth.database }}
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-mariadb
                  key: mariadb-password
            - name: DB_CLIENT
              value: mysql
            - name: DB_HOST
              value: {{ template "directus.fullname" . }}-mariadb
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- tpl (toYaml .Values.extraEnvVars) $ | nindent 12 }}
            {{- end }}
      {{- if .Values.snapshot }}
        - name: {{ .Chart.Name }}-schema-snapshot
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node"]
          args: ["/directus/cli.js", "schema", "snapshot", "--format", "yaml", "-y", "/startup-snapshot/snapshot.yaml"]
          env:
            {{- if .Values.ingress.enabled }}
            - name: PUBLIC_URL
              value: http{{ if .Values.ingress.tls }}s{{ end }}://{{(index .Values.ingress.hosts 0).host }}
            {{- end }}
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-secrets
                  key: key
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-secrets
                  key: secret
            {{- if .Values.mariadb.enabled }}
            - name: DB_DATABASE
              value: {{ .Values.mariadb.auth.database }}
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-mariadb
                  key: mariadb-password
            - name: DB_CLIENT
              value: mysql
            - name: DB_HOST
              value: {{ template "directus.fullname" . }}-mariadb
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- tpl (toYaml .Values.extraEnvVars) $ | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /startup-snapshot
              name: startup-snapshot
      {{- end }} 
      {{- if .Values.initContainers }}
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }} 
      containers:
        {{- if .Values.sidecars }}
{{ toYaml .Values.sidecars | indent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node"]
          args: ["/directus/cli.js", "start"]
          env:
            {{- if .Values.ingress.enabled }}
            - name: PUBLIC_URL
              value: http{{ if .Values.ingress.tls }}s{{ end }}://{{(index .Values.ingress.hosts 0).host }}
            {{- end }}
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-secrets
                  key: key
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-secrets
                  key: secret
            {{- if .Values.mariadb.enabled }}
            - name: DB_DATABASE
              value: {{ .Values.mariadb.auth.database }}
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.fullname" . }}-mariadb
                  key: mariadb-password
            - name: DB_CLIENT
              value: mysql
            - name: DB_HOST
              value: {{ template "directus.fullname" . }}-mariadb
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- tpl (toYaml .Values.extraEnvVars) $ | nindent 12 }}
            {{- end }}
          volumeMounts:
 {{- if .Values.snapshot }}
            - mountPath: /startup-snapshot
              name: startup-snapshot
{{- end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
{{- end }}
          ports:
            - name: http
              containerPort: 8055
              protocol: TCP
          {{- if .Values.startupProbe.enabled }} 
          startupProbe:
            httpGet:
              path: /server/health/
              port: http
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            httpGet:
              path: /server/health/
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /server/health/
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
{{- if .Values.snapshot }}
      - name: startup-snapshot
        emptyDir: {}
{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}