apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "directus.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
data:
  key: {{ .Values.key | toString | b64enc  }}
  secret: {{ .Values.secret | toString | b64enc  }}