name: Helm unit test
on:
  push:
    branches: ["unit-tests"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: d3adb5/helm-unittest-action@v2
        with:
          install-mode: force
          helm-version: v3.8.0
          github-token: ${{ secrets.GITHUB_TOKEN }}